import 'package:bloc/bloc.dart';
import 'package:flutter/material.dart';
import 'package:goal_master/features/auth/data/repo/auth_repo.dart';
import 'package:goal_master/utils/input_validator.dart';
part 'register_state.dart';

/// Signing up, one question at a time.
///
/// Two fields are gone from what the customer fills in. The account handle is
/// generated by the backend — they never see it, and nothing signs in by it.
/// The password confirmation is gone too: typing the same thing twice catches
/// a typo the show/hide toggle catches better, at the cost of a whole extra
/// screen.
///
/// Each step validates only its own field, so the customer hears about a
/// problem while they are still looking at it — rather than reaching the end
/// and being sent back.
class RegisterCubit extends Cubit<RegisterState> {
  RegisterCubit(this._repo) : super(RegisterInitial());
  final AuthRepo _repo;

  final nameController = TextEditingController();
  final phoneController = TextEditingController();
  final passwordController = TextEditingController();

  /// The name, for greeting them on the next step.
  String get firstName {
    final full = nameController.text.trim();
    if (full.isEmpty) return '';
    return full.split(RegExp(r'\s+')).first;
  }

  /// Whether step one may be left. Emits the reason if not.
  bool validateName() {
    final error =
        InputValidator.validateName(nameController.text, minLength: 2);
    if (error != null) {
      emit(RegisterError(error));
      return false;
    }
    emit(RegisterInitial());
    return true;
  }

  bool validatePhone() {
    final error = InputValidator.validatePhoneNumber(phoneController.text);
    if (error != null) {
      emit(RegisterError(error));
      return false;
    }
    emit(RegisterInitial());
    return true;
  }

  bool validatePassword() {
    final error = InputValidator.validatePassword(passwordController.text);
    if (error != null) {
      emit(RegisterError(error));
      return false;
    }
    emit(RegisterInitial());
    return true;
  }

  Future<void> register() async {
    // Re-checked here, not only per step: a customer can walk back and edit
    // an earlier answer, and the submit must judge what is actually there.
    if (!validateName() || !validatePhone() || !validatePassword()) return;

    emit(RegisterLoading());

    final result = await _repo.register(
      name: nameController.text.trim(),
      password: passwordController.text.trim(),
      phone: phoneController.text.trim(),
    );

    result.fold(
      (error) => emit(RegisterError(error.errMessage)),
      (_) => emit(RegisterSuccess()),
    );
  }

  @override
  Future<void> close() {
    nameController.dispose();
    phoneController.dispose();
    passwordController.dispose();
    return super.close();
  }
}
