# تحديد الحد الأدنى لإصدار iOS المطلوب لتوافق المكتبات مثل google_maps_flutter_ios
platform :ios, '15.0'

# تعطيل إرسال إحصائيات CocoaPods لتحسين سرعة build
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# تحديد إعدادات المشروع
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# مسار إعدادات Xcode التي يتم توليدها من Flutter
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# تحميل الأدوات المساعدة لـ Flutter
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# إعداد CocoaPods لـ Flutter
flutter_ios_podfile_setup

# إعدادات الهدف الرئيسي للتطبيق
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# إعدادات إضافية بعد تثبيت البودات
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
